from pathlib import Path
import sys, pandas as pd

ROOT = Path(r"c:\Users\Arkodeep\Desktop\hackerrank-orchestrate-september26-main\hackerrank-orchestrate-september26-main")
sys.path.insert(0, str(ROOT / 'code_v5_extract' / 'code'))
from main import Engine

eng = Engine(ROOT / 'dataset')
truth = pd.read_csv(ROOT / 'dataset' / 'sample_requests.csv')
req1 = truth.iloc[0]
profile = eng.profiles[eng.profiles.user_id == req1.user_id].iloc[0]
print("Profile:")
print(profile)

print("\nMessages for user_01:")
print(eng.messages[eng.messages.user_id == req1.user_id])

print("\nEvents for user_01 around/after request_date:")
rd = pd.Timestamp(req1.request_date)
ev = eng.events[(eng.events.user_id == req1.user_id) & (eng.events.settlement_date >= rd - pd.Timedelta(days=10))]
print(ev[['event_id', 'event_date', 'settlement_date', 'amount', 'currency', 'direction', 'category', 'status', 'flexibility', 'description']])

flows = eng.base_cashflows(profile, rd)
print(f"\nFlows generated by Engine ({len(flows)}):")
for f in flows:
    print(f)

print(f"\nsimulate(profile, rd, flows, [(rd, req1.requested_amount)]):")
ok, minseen = eng.simulate(profile, rd, flows, [(rd, float(req1.requested_amount))])
print("ok:", ok, "minseen:", minseen, "minbal:", profile.minimum_balance_to_keep)
